repos:

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: ["--verbose"]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length", "100", "--preview", "--skip-string-normalization"]

  - repo: local
    hooks:
      - id: fix-tabs-in-cmakelists
        name: Fix tabs in CMakeLists.txt
        entry: bash -c 'for file in "$@"; do sed -i"" -e "s/\t/  /g" "$file"; done'
        language: system
        types: [text]
        files: ^.*CMakeLists\.txt$
