so101_leader_ros2_bridge:
  ros__parameters:
    port: "/dev/ttyACM0"
    id: "leader"
    calibration_dir: "/home/anton/ros2_ws/src/so101_ros2/so101_ros2_bridge/config/calibration/leader.json"
    use_degrees: true
    # max_relative_target: 10 # default is none
    disable_torque_on_disconnect: true
    publish_rate: 50.0

