name: Clang Format

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Install ROS 2 development tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ros-humble-desktop
      - name: Update rosdep
        shell: bash
        run: rosdep update
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          rosdep install --from-paths . --ignore-src -r -y
      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+
        env:
          BUILD_TESTING: '1'
      - name: Run clang-format
        run: colcon test


